# Generated by Django 4.2.3 on 2023-07-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_remove_patientuser_id_patientuser_patientid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.IntegerField()),
                ('labid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.labinfo')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.patientuser')),
            ],
        ),
    ]
