# Generated by Django 4.2.3 on 2023-07-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_patientuser_patientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientuser',
            name='id',
        ),
        migrations.AddField(
            model_name='patientuser',
            name='patientid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labinfo',
            name='labid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
