# Generated by Django 4.2.3 on 2023-07-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='testid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
